name: CI Pipeline 3

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    # 4. Configurar PYTHONPATH
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
    - name: Debug PYTHONPATH
      run: echo $PYTHONPATH

    # 5. Ejecutar tests con pytest
    - name: Run unit tests
      run: pytest --maxfail=3 --disable-warnings

    # 6. Generar reporte de cobertura
    - name: Check code coverage
      run: |
        coverage run -m pytest
        coverage report
